### ISSUE TITLE
Contribute for Hacktoberfest2022

### ISSUE THREAD

**Issue by 1Alisha** [1Alisha/HACKTOBERFEST-22#12]
Make your first PR! ~ A beginner-friendly repository made specifically for open-source beginners. Add any program under any language (it can be anything from a hello-world program to a complex data structure algorithm) or update the existing one. Just make sure you add the program under the correct language directory. 
Make your Contribution towards hacktoberfest2022
Happy coding :)

**Comment by 1Alisha** [comment]
All valid PRs will be accepted
Don't forget to star this repository and follow me

**Comment by aminabrhm** [comment]
Hey i would love to contribute

**Comment by 1Alisha** [comment]
> Hey i would love to contribute

Sure go ahead

**Comment by Akshat-Salar** [comment]
Please Assign me

**Comment by 1Alisha** [comment]
@Akshat-Salar  Go ahead .. I have assigned you

**Comment by ashikjhonson** [comment]
Would you like to assign me

**Comment by rahul-gargcoder** [comment]
please assign me

**Comment by AKG1301** [comment]
please assign me

**Comment by AKG1301** [comment]
please assign this task to me

**Comment by AKG1301** [comment]
done.
link: https://github.com/1Alisha/HACKTOBERFEST-22/pull/60#issue-1408243297

**Comment by abhishekb13402** [comment]
Please Assign me

**Comment by shaheervk786** [comment]
Can u assign me please?

**Comment by Aditya-Kumar-Sahu** [comment]
Hello, I have done a little contribution, please check PR #96

**Comment by rittik29** [comment]
Hey I want to contribute 
please assign me this issue

**Comment by ZeeshanK07** [comment]
Hi Alisha, I have a contributed a programe on this issue. Please review #113 once 🙂
